var annotated_dup =
[
    [ "CW", "namespace_c_w.html", [
      [ "Common", "namespace_c_w_1_1_common.html", [
        [ "CwCameraLook", "class_c_w_1_1_common_1_1_cw_camera_look.html", "class_c_w_1_1_common_1_1_cw_camera_look" ],
        [ "CwCameraMove", "class_c_w_1_1_common_1_1_cw_camera_move.html", "class_c_w_1_1_common_1_1_cw_camera_move" ],
        [ "CwCameraPivot", "class_c_w_1_1_common_1_1_cw_camera_pivot.html", "class_c_w_1_1_common_1_1_cw_camera_pivot" ],
        [ "CwDemo", "class_c_w_1_1_common_1_1_cw_demo.html", "class_c_w_1_1_common_1_1_cw_demo" ],
        [ "CwDemoButton", "class_c_w_1_1_common_1_1_cw_demo_button.html", "class_c_w_1_1_common_1_1_cw_demo_button" ],
        [ "CwDemoButtonBuilder", "class_c_w_1_1_common_1_1_cw_demo_button_builder.html", "class_c_w_1_1_common_1_1_cw_demo_button_builder" ],
        [ "CwLightIntensity", "class_c_w_1_1_common_1_1_cw_light_intensity.html", "class_c_w_1_1_common_1_1_cw_light_intensity" ],
        [ "CwRotate", "class_c_w_1_1_common_1_1_cw_rotate.html", "class_c_w_1_1_common_1_1_cw_rotate" ],
        [ "CwChild", "class_c_w_1_1_common_1_1_cw_child.html", "class_c_w_1_1_common_1_1_cw_child" ],
        [ "CwDepthTextureMode", "class_c_w_1_1_common_1_1_cw_depth_texture_mode.html", "class_c_w_1_1_common_1_1_cw_depth_texture_mode" ],
        [ "CwFollow", "class_c_w_1_1_common_1_1_cw_follow.html", "class_c_w_1_1_common_1_1_cw_follow" ],
        [ "CwInputManager", "class_c_w_1_1_common_1_1_cw_input_manager.html", "class_c_w_1_1_common_1_1_cw_input_manager" ],
        [ "CwRenderTextureManager", "class_c_w_1_1_common_1_1_cw_render_texture_manager.html", "class_c_w_1_1_common_1_1_cw_render_texture_manager" ],
        [ "CwRoot", "class_c_w_1_1_common_1_1_cw_root.html", "class_c_w_1_1_common_1_1_cw_root" ],
        [ "CwSeedAttribute", "class_c_w_1_1_common_1_1_cw_seed_attribute.html", null ],
        [ "CwGuide", "class_c_w_1_1_common_1_1_cw_guide.html", "class_c_w_1_1_common_1_1_cw_guide" ],
        [ "CwShaderBundle", "class_c_w_1_1_common_1_1_cw_shader_bundle.html", "class_c_w_1_1_common_1_1_cw_shader_bundle" ]
      ] ]
    ] ],
    [ "SpaceGraphicsToolkit", "namespace_space_graphics_toolkit.html", [
      [ "Atmosphere", "namespace_space_graphics_toolkit_1_1_atmosphere.html", [
        [ "SgtAtmosphere", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere.html", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere" ],
        [ "SgtAtmosphereDepthTex", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_depth_tex.html", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_depth_tex" ],
        [ "SgtAtmosphereHeight", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_height.html", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_height" ],
        [ "SgtAtmosphereLightingTex", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_lighting_tex.html", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_lighting_tex" ],
        [ "SgtAtmosphereModel", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_model.html", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_model" ],
        [ "SgtAtmosphereScatteringTex", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_scattering_tex.html", "class_space_graphics_toolkit_1_1_atmosphere_1_1_sgt_atmosphere_scattering_tex" ]
      ] ],
      [ "Billboard", "namespace_space_graphics_toolkit_1_1_billboard.html", [
        [ "SgtBillboard", "class_space_graphics_toolkit_1_1_billboard_1_1_sgt_billboard.html", "class_space_graphics_toolkit_1_1_billboard_1_1_sgt_billboard" ],
        [ "SgtFastBillboard", "class_space_graphics_toolkit_1_1_billboard_1_1_sgt_fast_billboard.html", "class_space_graphics_toolkit_1_1_billboard_1_1_sgt_fast_billboard" ],
        [ "SgtFastBillboardManager", "class_space_graphics_toolkit_1_1_billboard_1_1_sgt_fast_billboard_manager.html", "class_space_graphics_toolkit_1_1_billboard_1_1_sgt_fast_billboard_manager" ]
      ] ],
      [ "Cloudsphere", "namespace_space_graphics_toolkit_1_1_cloudsphere.html", [
        [ "SgtCloudsphere", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere.html", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere" ],
        [ "SgtCloudsphereDepthTex", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_depth_tex.html", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_depth_tex" ],
        [ "SgtCloudsphereLightingTex", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_lighting_tex.html", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_lighting_tex" ],
        [ "SgtCloudsphereModel", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_model.html", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_model" ],
        [ "SgtCloudsphereNearTex", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_near_tex.html", "class_space_graphics_toolkit_1_1_cloudsphere_1_1_sgt_cloudsphere_near_tex" ]
      ] ],
      [ "LightAndShadow", "namespace_space_graphics_toolkit_1_1_light_and_shadow.html", [
        [ "SgtLight", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_light.html", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_light" ],
        [ "SgtShadow", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow.html", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow" ],
        [ "SgtShadowLayer", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_layer.html", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_layer" ],
        [ "SgtShadowRing", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_ring.html", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_ring" ],
        [ "SgtShadowRingFilter", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_ring_filter.html", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_ring_filter" ],
        [ "SgtShadowSphere", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_sphere.html", "class_space_graphics_toolkit_1_1_light_and_shadow_1_1_sgt_shadow_sphere" ]
      ] ],
      [ "Shapes", "namespace_space_graphics_toolkit_1_1_shapes.html", [
        [ "SgtShape", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape.html", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape" ],
        [ "SgtShapeBox", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_box.html", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_box" ],
        [ "SgtShapeGroup", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_group.html", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_group" ],
        [ "SgtShapeSphere", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_sphere.html", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_sphere" ],
        [ "SgtShapeTorus", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_torus.html", "class_space_graphics_toolkit_1_1_shapes_1_1_sgt_shape_torus" ]
      ] ],
      [ "SgtPlanet", "class_space_graphics_toolkit_1_1_sgt_planet.html", "class_space_graphics_toolkit_1_1_sgt_planet" ],
      [ "SgtPlanetWaterGradient", "class_space_graphics_toolkit_1_1_sgt_planet_water_gradient.html", "class_space_graphics_toolkit_1_1_sgt_planet_water_gradient" ],
      [ "SgtPlanetWaterTexture", "class_space_graphics_toolkit_1_1_sgt_planet_water_texture.html", "class_space_graphics_toolkit_1_1_sgt_planet_water_texture" ],
      [ "SgtCameraMove", "class_space_graphics_toolkit_1_1_sgt_camera_move.html", "class_space_graphics_toolkit_1_1_sgt_camera_move" ],
      [ "SgtCameraPath", "class_space_graphics_toolkit_1_1_sgt_camera_path.html", "class_space_graphics_toolkit_1_1_sgt_camera_path" ],
      [ "SgtDemo", "class_space_graphics_toolkit_1_1_sgt_demo.html", "class_space_graphics_toolkit_1_1_sgt_demo" ],
      [ "SgtDragPitchYaw", "class_space_graphics_toolkit_1_1_sgt_drag_pitch_yaw.html", "class_space_graphics_toolkit_1_1_sgt_drag_pitch_yaw" ],
      [ "SgtPrefabSwitcher", "class_space_graphics_toolkit_1_1_sgt_prefab_switcher.html", "class_space_graphics_toolkit_1_1_sgt_prefab_switcher" ],
      [ "SgtBackgroundMesh", "class_space_graphics_toolkit_1_1_sgt_background_mesh.html", "class_space_graphics_toolkit_1_1_sgt_background_mesh" ],
      [ "SgtDragReceiver", "class_space_graphics_toolkit_1_1_sgt_drag_receiver.html", "class_space_graphics_toolkit_1_1_sgt_drag_receiver" ],
      [ "SgtDragSource", "class_space_graphics_toolkit_1_1_sgt_drag_source.html", "class_space_graphics_toolkit_1_1_sgt_drag_source" ],
      [ "SgtGravityReceiver", "class_space_graphics_toolkit_1_1_sgt_gravity_receiver.html", "class_space_graphics_toolkit_1_1_sgt_gravity_receiver" ],
      [ "SgtGravitySource", "class_space_graphics_toolkit_1_1_sgt_gravity_source.html", "class_space_graphics_toolkit_1_1_sgt_gravity_source" ],
      [ "SgtLightFlicker", "class_space_graphics_toolkit_1_1_sgt_light_flicker.html", "class_space_graphics_toolkit_1_1_sgt_light_flicker" ],
      [ "SgtProceduralForce", "class_space_graphics_toolkit_1_1_sgt_procedural_force.html", "class_space_graphics_toolkit_1_1_sgt_procedural_force" ],
      [ "SgtProceduralScale", "class_space_graphics_toolkit_1_1_sgt_procedural_scale.html", "class_space_graphics_toolkit_1_1_sgt_procedural_scale" ],
      [ "SgtProceduralSpin", "class_space_graphics_toolkit_1_1_sgt_procedural_spin.html", "class_space_graphics_toolkit_1_1_sgt_procedural_spin" ],
      [ "SgtProceduralTint", "class_space_graphics_toolkit_1_1_sgt_procedural_tint.html", "class_space_graphics_toolkit_1_1_sgt_procedural_tint" ],
      [ "SgtProceduralTorque", "class_space_graphics_toolkit_1_1_sgt_procedural_torque.html", "class_space_graphics_toolkit_1_1_sgt_procedural_torque" ],
      [ "SgtProximityDrag", "class_space_graphics_toolkit_1_1_sgt_proximity_drag.html", "class_space_graphics_toolkit_1_1_sgt_proximity_drag" ],
      [ "SgtRaycastTranslate", "class_space_graphics_toolkit_1_1_sgt_raycast_translate.html", "class_space_graphics_toolkit_1_1_sgt_raycast_translate" ],
      [ "SgtSimpleOrbit", "class_space_graphics_toolkit_1_1_sgt_simple_orbit.html", "class_space_graphics_toolkit_1_1_sgt_simple_orbit" ],
      [ "SgtSimpleScaler", "class_space_graphics_toolkit_1_1_sgt_simple_scaler.html", "class_space_graphics_toolkit_1_1_sgt_simple_scaler" ],
      [ "IOverridableSharedMaterial", "interface_space_graphics_toolkit_1_1_i_overridable_shared_material.html", "interface_space_graphics_toolkit_1_1_i_overridable_shared_material" ],
      [ "SgtAtlas", "class_space_graphics_toolkit_1_1_sgt_atlas.html", "class_space_graphics_toolkit_1_1_sgt_atlas" ],
      [ "SgtCamera", "class_space_graphics_toolkit_1_1_sgt_camera.html", "class_space_graphics_toolkit_1_1_sgt_camera" ],
      [ "SgtCameraState", "class_space_graphics_toolkit_1_1_sgt_camera_state.html", "class_space_graphics_toolkit_1_1_sgt_camera_state" ],
      [ "SgtLightPointer", "class_space_graphics_toolkit_1_1_sgt_light_pointer.html", "class_space_graphics_toolkit_1_1_sgt_light_pointer" ],
      [ "SgtLong3", "struct_space_graphics_toolkit_1_1_sgt_long3.html", "struct_space_graphics_toolkit_1_1_sgt_long3" ],
      [ "SgtLongBounds", "struct_space_graphics_toolkit_1_1_sgt_long_bounds.html", "struct_space_graphics_toolkit_1_1_sgt_long_bounds" ],
      [ "SgtLongRect", "struct_space_graphics_toolkit_1_1_sgt_long_rect.html", "struct_space_graphics_toolkit_1_1_sgt_long_rect" ],
      [ "SgtOcclusionScaler", "class_space_graphics_toolkit_1_1_sgt_occlusion_scaler.html", "class_space_graphics_toolkit_1_1_sgt_occlusion_scaler" ],
      [ "SgtPoolComponent", "class_space_graphics_toolkit_1_1_sgt_pool_component.html", "class_space_graphics_toolkit_1_1_sgt_pool_component" ],
      [ "SgtProcedural", "class_space_graphics_toolkit_1_1_sgt_procedural.html", "class_space_graphics_toolkit_1_1_sgt_procedural" ],
      [ "SgtProperties", "class_space_graphics_toolkit_1_1_sgt_properties.html", "class_space_graphics_toolkit_1_1_sgt_properties" ],
      [ "SgtRenderQueue", "struct_space_graphics_toolkit_1_1_sgt_render_queue.html", "struct_space_graphics_toolkit_1_1_sgt_render_queue" ],
      [ "SgtShaderProperties", "class_space_graphics_toolkit_1_1_sgt_shader_properties.html", "class_space_graphics_toolkit_1_1_sgt_shader_properties" ],
      [ "SgtSharedMaterial", "class_space_graphics_toolkit_1_1_sgt_shared_material.html", "class_space_graphics_toolkit_1_1_sgt_shared_material" ]
    ] ],
    [ "AudioListener", "class_audio_listener.html", null ],
    [ "Checkpoint", "class_checkpoint.html", null ],
    [ "Credits", "class_credits.html", "class_credits" ],
    [ "DeathManagerGrapple", "class_death_manager_grapple.html", "class_death_manager_grapple" ],
    [ "DeathManagerHammer", "class_death_manager_hammer.html", "class_death_manager_hammer" ],
    [ "DoorButton", "class_door_button.html", "class_door_button" ],
    [ "Grapple", "class_grapple.html", "class_grapple" ],
    [ "GUI_Demo", "class_g_u_i___demo.html", "class_g_u_i___demo" ],
    [ "Hammer", "class_hammer.html", "class_hammer" ],
    [ "HammerAnimation", "class_hammer_animation.html", "class_hammer_animation" ],
    [ "Hook", "class_hook.html", "class_hook" ],
    [ "MainMenu", "class_main_menu.html", "class_main_menu" ],
    [ "MouseLookGrapple", "class_mouse_look_grapple.html", "class_mouse_look_grapple" ],
    [ "MouseLookHammer", "class_mouse_look_hammer.html", "class_mouse_look_hammer" ],
    [ "Options", "class_options.html", "class_options" ],
    [ "PauseMenu", "class_pause_menu.html", "class_pause_menu" ],
    [ "PickUpGrapple", "class_pick_up_grapple.html", "class_pick_up_grapple" ],
    [ "PickUpHammer", "class_pick_up_hammer.html", "class_pick_up_hammer" ],
    [ "PlayerMovementGrapple", "class_player_movement_grapple.html", "class_player_movement_grapple" ],
    [ "PlayerMovementHammer", "class_player_movement_hammer.html", "class_player_movement_hammer" ],
    [ "PressurePlate", "class_pressure_plate.html", null ],
    [ "PreTutorial", "class_pre_tutorial.html", "class_pre_tutorial" ],
    [ "Scoreboard", "class_scoreboard.html", "class_scoreboard" ],
    [ "Story", "class_story.html", "class_story" ],
    [ "SynchBorder", "class_synch_border.html", null ],
    [ "SynchGoal", "class_synch_goal.html", "class_synch_goal" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "TutorialHint", "class_tutorial_hint.html", null ],
    [ "TutorialSynchGoal", "class_tutorial_synch_goal.html", null ],
    [ "TutorialText", "class_tutorial_text.html", "class_tutorial_text" ],
    [ "TutorialTextController", "class_tutorial_text_controller.html", "class_tutorial_text_controller" ],
    [ "TutorialTextSynchBorder", "class_tutorial_text_synch_border.html", "class_tutorial_text_synch_border" ],
    [ "TypewritingUI", "class_typewriting_u_i.html", null ],
    [ "XInputTestCS", "class_x_input_test_c_s.html", null ]
];